<template>
  <b-carousel
    id="carousel-fade"
    style="text-shadow: 0 0 2px #000;"
    fade
    indicators
    img-width="1024"
    img-height="480"
  >
    <b-carousel-slide
      caption=""
      img-src="~assets/images/image5.jpg"
    ></b-carousel-slide>
    <b-carousel-slide
      caption=""
      img-src="~assets/images/image5.jpg"
    ></b-carousel-slide>
  </b-carousel>
</template>
